### ISSUE TITLE
addTracks parameters are incorrect

### ISSUE THREAD

**Issue by calebvetter** [NTProductions/pr-moveToTrack-addTracks#1]
The correct params are as follows:

addTrack(
    number of video tracks to add,
    position to add video tracks (zero-based index),
    number of audio tracks to add,
    audio track type (see legend below),
    position to add audio tracks (zero-based index),
    number of submixes to add,
    submix type (see legend below),
    position to add submix (zero-based index))

And then the audio track / submix types are as follows:
0: Mono
1: Standard
2: 5.1
3: Stereo

**Comment by NTProductions** [comment]
Great @calebvetter! Updated!

**Comment by calebvetter** [comment]
Saw the new code. Allllllmost correct, haha. Just add “audio track type” after parameter 3 but before parameter 4. The audio track type is parameter 4, which shifts “audio track insert position” to parameter 5.
